---
- hosts: monitoring
  roles:<% for ( var i = 0; i < monitoringStack.length; i++) { %>
  - <%= monitoringStack[i] -%>
  <% } %>

- hosts: db-master
  roles:
   - { role: mysql, mysql_dbye: [{name: soma}], mysql_users: [{name: soma, pass: foobar, priv: "*.*:ALL"}], mysql_db_id: 8 }
   - telegraf

- hosts: cache-servers
  roles:
  - redis
  - telegraf


- hosts: api-servers
  roles: <% for ( var i = 0; i < apiStack.length; i++) { %>
  - <%= apiStack[i] -%>
  <% } %>
  - deploy-code
